{% raw -%}
---
- name: Deploy application
  hosts: webservers
  remote_user: "{{ application_user }}"
  vars_files:
    - ansible_vars/base.yml
    - ansible_vars/{{ env }}.yml

  roles:
    - carlosbuenosvinos.ansistrano-deploy
{%- endraw %}
