{% raw -%}
- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  become: yes
  become_user: root
  remote_user: ubuntu 
  vars_files:
    - ansible_vars/base.yml
    - ansible_vars/staging.yml
  roles:
    - common
    - web
    - ANXS.postgresql
    - app
{%- endraw %}
{%- if cookiecutter.use_celery == "y" %}
    - celery
{%- endif %}
